name: Jira Issue Link

on:
  issues:
    types:
      - opened

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Jira Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Jira Issue Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: HOMEAT
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.html_url }}
          fields: '{"labels": ["프론트엔드"]}'

      - name: Get New Branch Name
        id: new-branch
        shell: python
        run: |
          for label in ${{ toJson(github.event.issue.labels.*.name) }}:
            if ':' in label:
              branch_type = label.split(':')[-1].strip()
              ticket_num = '${{ steps.create.outputs.issue }}'
              print(f"::set-output name=name::{branch_type}/{ticket_num}")

      - name: Create New Branch with Ticket Number
        run: |
          git checkout -b ${{ steps.new-branch.outputs.name }}
          git push origin ${{ steps.new-branch.outputs.name }}
